"""implementando training sheet

Revision ID: 07503aba21ad
Revises: b12e25d2bb71
Create Date: 2025-05-29 18:10:46.921307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07503aba21ad'
down_revision: Union[str, None] = 'b12e25d2bb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainingsheetexerciselink')
    op.drop_table('trainingsheetuserlink')
    op.drop_table('trainingsheet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingsheet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('trainingsheet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('focus_area', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level', postgresql.ENUM('Beginner', 'Intermediate', 'Advanced', name='level_exercise'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trainingsheet_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trainingsheetuserlink',
    sa.Column('training_sheet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['training_sheet_id'], ['trainingsheet.id'], name=op.f('trainingsheetuserlink_training_sheet_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('trainingsheetuserlink_user_id_fkey')),
    sa.PrimaryKeyConstraint('training_sheet_id', 'user_id', name=op.f('trainingsheetuserlink_pkey'))
    )
    op.create_table('trainingsheetexerciselink',
    sa.Column('training_sheet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], name=op.f('trainingsheetexerciselink_exercise_id_fkey')),
    sa.ForeignKeyConstraint(['training_sheet_id'], ['trainingsheet.id'], name=op.f('trainingsheetexerciselink_training_sheet_id_fkey')),
    sa.PrimaryKeyConstraint('training_sheet_id', 'exercise_id', name=op.f('trainingsheetexerciselink_pkey'))
    )
    # ### end Alembic commands ###
