"""nullable em equipament exercise

Revision ID: 682227ea3338
Revises: dbc96f5514a3
Create Date: 2025-05-27 16:04:29.833729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682227ea3338'
down_revision: Union[str, None] = 'dbc96f5514a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'equipment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
