"""add_notes_to_executed_daily_training

Revision ID: 6e4b47e82742
Revises: 682227ea3338
Create Date: 2025-05-29 10:55:39.488730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e4b47e82742'
down_revision: Union[str, None] = '682227ea3338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('executeddailytraining', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('executeddailytraining', 'notes')
    # ### end Alembic commands ###
