"""alterando o tipo do level no trainingsheet

Revision ID: b12e25d2bb71
Revises: 6e4b47e82742
Create Date: 2025-05-29 13:17:57.878012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12e25d2bb71'
down_revision: Union[str, None] = '6e4b47e82742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainingsheet', 'level',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Beginner', 'Intermediate', 'Advanced', name='level_exercise'),
               existing_nullable=False,
               postgresql_using="level::level_exercise"
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainingsheet', 'level',
               existing_type=sa.Enum('Beginner', 'Intermediate', 'Advanced', name='level_exercise'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
