"""add trainingsheet

Revision ID: dbc96f5514a3
Revises: c4d046d26a7b
Create Date: 2025-05-27 15:05:21.336681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbc96f5514a3'
down_revision: Union[str, None] = 'c4d046d26a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainingsheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('focus_area', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trainingsheetexerciselink',
    sa.Column('training_sheet_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['training_sheet_id'], ['trainingsheet.id'], ),
    sa.PrimaryKeyConstraint('training_sheet_id', 'exercise_id')
    )
    op.create_table('trainingsheetuserlink',
    sa.Column('training_sheet_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['training_sheet_id'], ['trainingsheet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('training_sheet_id', 'user_id')
    )
    op.create_foreign_key(None, 'executedexercise', 'exercise', ['id_exercise'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'executedexercise', type_='foreignkey')
    op.drop_table('trainingsheetuserlink')
    op.drop_table('trainingsheetexerciselink')
    op.drop_table('trainingsheet')
    # ### end Alembic commands ###
